defaults:
  - _self_
  - task: tidybot2_actpp

name: train_unet_tidybot2
_target_: actpp.actpp_workspace.ACTWorkspace

task_name: ${task.name}
shape_meta: ${task.shape_meta}
exp_name: "default"

n_action_steps: 8

policy:
  action_dim: 13

  # backbone
  backbone: resnet18
  frozen_backbone: False
  dilation: False
  position_embedding: sine # Options: none, sine, learned
  camera_names: # for now, only the number of names matters, but they need to be concatenated in a consistent order
    - base_image
    - wrist_image
  
  # tranformer params
  no_encoder: False
  enc_layers: 4
  dec_layers: 7
  dim_feedforward: 2048
  hidden_dim: 256
  dropout: 0.1
  nheads: 8
  num_queries: 8
  pre_norm: False

  # vqvae params
  vq: False
  vq_class: 12 # int
  vq_dim: 64

  masks: False

optimizer:
  lr: 3.0e-4
  lr_backbone: 3.0e-5
  betas: [0.95, 0.999]
  eps: 1.0e-8
  weight_decay: 1.0e-6

training:
  device: "cuda:0"
  kl_weight: 0.1
  seed: 42
  debug: False
  resume: False
  # optimization
  lr_scheduler: cosine
  lr_warmup_steps: 2000
  num_epochs: 100000
  gradient_accumulate_every: 1
  # EMA destroys performance when used with BatchNorm
  # replace BatchNorm with GroupNorm.
  use_ema: True
  freeze_encoder: False
  # training loop control
  # in epochs
  rollout_every: 10
  checkpoint_every: 50
  val_every: 1
  sample_every: 5
  # steps per epoch
  max_train_steps: null
  max_val_steps: null
  # misc
  tqdm_interval_sec: 1.0
  output_dir: data/test_actpp
  inference_mode: False
  online_rollouts: False

dataloader:
  batch_size: 64
  num_workers: 8
  shuffle: True
  pin_memory: True
  persistent_workers: True

val_dataloader:
  batch_size: 64
  num_workers: 8
  shuffle: False
  pin_memory: True
  persistent_workers: True

logging:
  project: tidybot2
  resume: False
  mode: online
  name: ${now:%Y.%m.%d-%H.%M.%S}_${name}_${task_name}
  tags: ["${name}", "${task_name}", "${exp_name}"]
  id: null
  group: null

checkpoint:
  topk:
    monitor_key: train_loss
    mode: min
    k: 20
    format_str: 'epoch={epoch:04d}-train_loss={train_loss:.3f}.ckpt'
  save_last_ckpt: True
  save_last_snapshot: False

multi_run:
  run_dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
  wandb_name_base: ${now:%Y.%m.%d-%H.%M.%S}_${name}_${task_name}

hydra:
  job:
    override_dirname: ${name}
  run:
    dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
  sweep:
    dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
    subdir: ${hydra.job.num}
